# Setup
name:         vinodpandey.com
tagline:      Random Thoughts of a Technology Enthusiast
baseurl:      ""

# Gems
gems:
  - jekyll-paginate
  - jekyll-redirect-from

#Others
markdown: kramdown
permalink: none